# Generated by Django 5.1.1 on 2024-12-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0002_listing_delete_offering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='rate',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
